version: "3"

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    environment:
      - REST_API_PROXY_SERVER=${REST_API_PROXY}
      - SERVER_HOST=${SERVER_HOST}
    restart: always
    # networks:
    #   - rest-network
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
    

# networks:
#    rest-network:
