version: "3"

services:
   frontend:
    #  image: php:drugdiscovery-base
    #  container_name: "drugdiscovery-base"
     build:
       context: .
       dockerfile: Dockerfile
     environment:
       - REST_API_PROXY_SERVER=${REST_API_PROXY_SERVER}
       - SERVER_HOST=${SERVER_HOST}
     restart: always
     networks:
       - rest-network
     ports:
       - "80:80"
    #  depends_on:
    #    - redial

  #  redial:
  #     # image: sirimullalab/redial-2020:latest
  #     # container_name: "sirimulla-redial"
  #     build: 
  #       context: .
  #     restart: always
  #     networks: 
  #       - rest-network

networks:
   rest-network:
